name: Events

on: 
    push: 
#   workflow_dispatch: 

    # schedule:
    # - cron: "*/1 * * * *"
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: ugobase
    IMAGE_NAME: github-actions-nginx

jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
        #   run: echo docker build -t ${{ env.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME}}/{{ env.IMAGE_NAME:latest}}
          run: echo docker build -t {{ vars.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME}}/{{ vars.IMAGE_NAME:latest}}

        - name: Docker Login
          run: echo docker login --username={{ vars.DOCKER_USERNAME}}  --password={{ secrets.DOCKER_PASSWORD}}

        - name: Docker Push
          run: echo docker push {{ vars.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME}}/{{ vars.IMAGE_NAME:latest}}

    docker_run:
      runs-on: ubuntu-latest
      needs: docker_build
      concurrency: 
        group: production
        cancel-in-progress: true

      timeout-minutes: 1
      steps:
      - name: Docker Run
        run: | 
            echo docker run -d -p 8080:80 {{ vars.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME}}/{{ vars.IMAGE_NAME:latest}}
            sleep 300s