name: First action

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: hello world
              run: echo "hello world"

            - name: List files
              run: ls
            - name: List all files
              run: ls -a
        

            - name: Read files
              run: cat README.md