name: First action

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List and Read Files
              run: |
                echo "hello world"
                ls -ltra
                cat README.md

            - name: Install Cowsay And Generate Ascii
              run: |
               sudo apt install cowsay -y
               cowsay -f dragon "The Dragon Queen!!" >> snow.txt
               grep -i "dragon" snow.txt
               cat snow.txt

            - name: Read files
              run: cat README.md
            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: snow.txt
    second-job:
      needs: first-job
      runs-on: ubuntu-latest
      steps:
      - name: Validation
        uses: actions/download-artifact@v4
        with:
          name: my-artifact