name: Shell action

on: push

jobs:
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: shellscripting
              run: |
               chmod +x ascii.sh
               ./ascii.sh
        
    third-job:
        runs-on: ubuntu-latest
        needs: second-job
        steps:
            - name: parallel job
              run: |
                ls -ltra
                sleep 10
